# -*- coding: utf-8 -*-
# Datos integrados de Rulkanis

cartas_accion = [
    {"nombre": "BUFFO VIDA GRANDE", "nomenclatura": "BVG", "nivel": 5},
    {"nombre": "ATAQUE NORMAL + SANGRADO CERTERO", "nomenclatura": "AN+SC", "nivel": 5},
    {"nombre": "ATAQUE NORMAL PARALIZAR AZAR", "nomenclatura": "AN+PA", "nivel": 5},
    {
        "nombre": "Ataque normal + buffo defensa fuerte",
        "nomenclatura": "AN+BDF",
        "nivel": 5,
    },
    {"nombre": "Ataque normal + buffo suerte", "nomenclatura": "AN+BS", "nivel": 5},
    {
        "nombre": "Ataque normal +buffo limpieza azar",
        "nomenclatura": "AN+BLA",
        "nivel": 5,
    },
    {
        "nombre": "Ataque normal + buffo vida pequeño",
        "nomenclatura": "AN+BVP",
        "nivel": 5,
    },
    {"nombre": "Ataque ligero + congelar certero", "nomenclatura": "AL+CC", "nivel": 5},
    {
        "nombre": "Ataque ligero + buffo vida mediano",
        "nomenclatura": "AL+BVM",
        "nivel": 5,
    },
    {"nombre": "Ataque critico + sangrado azar", "nomenclatura": "AC+SA", "nivel": 5},
    {"nombre": "Ataque critico + congelar azar", "nomenclatura": "AC+CA", "nivel": 5},
    {"nombre": "Ataque critico + fuego certero", "nomenclatura": "AC+FC", "nivel": 5},
    {
        "nombre": "Ataque critico + paralizar certero",
        "nomenclatura": "AC+PC",
        "nivel": 5,
    },
    {
        "nombre": "Ataque critico + buffo defensa normal",
        "nomenclatura": "AC+BDN",
        "nivel": 5,
    },
    {"nombre": "Sangrado certero + fuego certero", "nomenclatura": "SC+FC", "nivel": 5},
    {
        "nombre": "Sangrado certero + paralizar certero",
        "nomenclatura": "SC+PC",
        "nivel": 5,
    },
    {
        "nombre": "Sangrado certero + buffo defensa normal",
        "nomenclatura": "SC+BDN",
        "nivel": 5,
    },
    {"nombre": "Sangrado azar + buffo suerte", "nomenclatura": "SA+BS", "nivel": 5},
    {
        "nombre": "Sangrado azar + buffo limpieza azar",
        "nomenclatura": "SA+BLA",
        "nivel": 5,
    },
    {
        "nombre": "Sangrado azar + buffo vida pequeño",
        "nomenclatura": "SA+BVP",
        "nivel": 5,
    },
    {
        "nombre": "Congelar certero +  bufo defensa ",
        "nomenclatura": "CC+BD",
        "nivel": 5,
    },
    {"nombre": "Congelar certero + robo carta", "nomenclatura": "CC+RC", "nivel": 5},
    {
        "nombre": "Congelar azar + buffo defensa fuerte",
        "nomenclatura": "CA+BDF",
        "nivel": 5,
    },
    {"nombre": "Congelar azar + buffo suerte ", "nomenclatura": "CA+BS", "nivel": 5},
    {
        "nombre": "Congelar azar + buffo limpieza azar",
        "nomenclatura": "CA+BLA",
        "nivel": 5,
    },
    {
        "nombre": "Congelar azar + buffo vida pequeño",
        "nomenclatura": "CA+BVP",
        "nivel": 5,
    },
    {
        "nombre": "Fuego certero + buffo defensa fuerte",
        "nomenclatura": "FC+BDF",
        "nivel": 5,
    },
    {"nombre": "Fuego certero + buffo suerte", "nomenclatura": "FC+BS", "nivel": 5},
    {
        "nombre": "Fuego certero + buffo vida pequeño",
        "nomenclatura": "FC+BVP",
        "nivel": 5,
    },
    {"nombre": "Fuego azar + buffo vida mediano", "nomenclatura": "FA+BVM", "nivel": 5},
    {
        "nombre": "Paralizar certero + buffo defensa fuerte",
        "nomenclatura": "PC+BDF",
        "nivel": 5,
    },
    {"nombre": "Paralizar certero + buffo suerte", "nomenclatura": "PC+BS", "nivel": 5},
    {
        "nombre": "Paralizar certero + buffo vida pequeño",
        "nomenclatura": "PC+BVP",
        "nivel": 5,
    },
    {
        "nombre": "Paralizar azar + buffo vida mediano",
        "nomenclatura": "PA+BVM",
        "nivel": 5,
    },
    {
        "nombre": "Buffo defensa + buffo vida mediano",
        "nomenclatura": "BD+BVM",
        "nivel": 5,
    },
    {
        "nombre": "Buffo defensa normal + buffo suerte",
        "nomenclatura": "BDN+BS",
        "nivel": 5,
    },
    {
        "nombre": "Buffo defensa normal + buffo vida pequeño",
        "nomenclatura": "BDN+BVP",
        "nivel": 5,
    },
    {"nombre": "Buffo vida mediano + robo carta", "nomenclatura": "BVM+RC", "nivel": 5},
    {"nombre": "CONGELAR CERTERO", "nomenclatura": "CC", "nivel": 4},
    {"nombre": "BUFFO VIDA MEDIANO", "nomenclatura": "BVM", "nivel": 4},
    {"nombre": "ATAQUE NORMAL + SANGRADO AZAR", "nomenclatura": "AN+SA", "nivel": 4},
    {"nombre": "ATAQUE NORMAL + CONGELAR AZAR", "nomenclatura": "AN+CA", "nivel": 4},
    {"nombre": "ATAQUE NORMAL + FUEGO CERTERO", "nomenclatura": "AN+FC", "nivel": 4},
    {"nombre": "ATAQUE NORMAL PARALIZAR CERTERO", "nomenclatura": "AN+PC", "nivel": 4},
    {
        "nombre": "ATAQUE NORMAL + buffo defensa normal",
        "nomenclatura": "AN+BDN",
        "nivel": 4,
    },
    {"nombre": "Ataque ligero + Sangrado certero", "nomenclatura": "AL+SC", "nivel": 4},
    {
        "nombre": "Ataque ligero + buffo defensa fuerte",
        "nomenclatura": "AL+BDF",
        "nivel": 4,
    },
    {"nombre": "Ataque ligero + buffo suerte ", "nomenclatura": "AL+BS", "nivel": 4},
    {"nombre": "Ataque ligero + limpieza azar", "nomenclatura": "AL+BLA", "nivel": 4},
    {
        "nombre": "Ataque ligero + buffo vida pequeño",
        "nomenclatura": "AL+BVP",
        "nivel": 4,
    },
    {"nombre": "Ataque critico + fuego azar ", "nomenclatura": "AC+FA", "nivel": 4},
    {"nombre": "Ataque critico + paralizar azar", "nomenclatura": "AC+PA", "nivel": 4},
    {"nombre": "Ataque critico + buffo defensa", "nomenclatura": "AC+BD", "nivel": 4},
    {"nombre": "Ataque critico + robar carta", "nomenclatura": "AC+RC", "nivel": 4},
    {"nombre": "Sangrado certero + buffo defensa", "nomenclatura": "SC+BD", "nivel": 4},
    {"nombre": "Sangrado certero + robo carta", "nomenclatura": "SC+RC", "nivel": 4},
    {"nombre": "Sangrado azar + congelar azar", "nomenclatura": "SA+CA", "nivel": 4},
    {
        "nombre": "Sangrado azar + buffo defensa normal",
        "nomenclatura": "SA+BDN",
        "nivel": 4,
    },
    {
        "nombre": "Congelar aza+ buffo defensa normal",
        "nomenclatura": "CA+BDN",
        "nivel": 4,
    },
    {
        "nombre": "Fuego certero +. Paralizar certero",
        "nomenclatura": "FC+PC",
        "nivel": 4,
    },
    {
        "nombre": "Fuego certero + buffo defensa normal",
        "nomenclatura": "FC+BDN",
        "nivel": 4,
    },
    {
        "nombre": "Fuego azar +. Buffo defensa fuerte",
        "nomenclatura": "FA+BDF",
        "nivel": 4,
    },
    {"nombre": "Fuego azar + buffo suerte ", "nomenclatura": "FA+BS", "nivel": 4},
    {
        "nombre": "Fuego azar  + buffo limpieza azar",
        "nomenclatura": "FA+BLA",
        "nivel": 4,
    },
    {"nombre": "Fuego azar + buffo vida pequeño", "nomenclatura": "FA+BVP", "nivel": 4},
    {
        "nombre": "Paralizar certero + buffo defensa normal",
        "nomenclatura": "PC+BDN",
        "nivel": 4,
    },
    {
        "nombre": "Paralizar azar + buffo defensa fuerte",
        "nomenclatura": "PA+BDF",
        "nivel": 4,
    },
    {"nombre": "Paralizar azar + buffo suerte", "nomenclatura": "PA+BS", "nivel": 4},
    {
        "nombre": "Paralizar azar + buffo limpieza azar",
        "nomenclatura": "PA+BLA",
        "nivel": 4,
    },
    {
        "nombre": "Paralizar azar + buffo vida pequeño",
        "nomenclatura": "PA+BVP",
        "nivel": 4,
    },
    {"nombre": "Buffo defensa + buffo suerte", "nomenclatura": "BD+BS", "nivel": 4},
    {
        "nombre": "Buffo defensa + buffo vida pequeño",
        "nomenclatura": "BD+BVP",
        "nivel": 4,
    },
    {
        "nombre": "Buffo defensa fuerte + robo carta",
        "nomenclatura": "BDF+RC",
        "nivel": 4,
    },
    {"nombre": "Buffo suerte + robo de carta", "nomenclatura": "BS+RC", "nivel": 4},
    {"nombre": "Buffo limpieza + robo carta", "nomenclatura": "BLA+RC", "nivel": 4},
    {
        "nombre": "Buffo vida pequeño + robo carta ",
        "nomenclatura": "BVP+RC",
        "nivel": 4,
    },
    {
        "nombre": "Sangrado azar + buffo defensa fuerte",
        "nomenclatura": "SA+BDF",
        "nivel": 4,
    },
    {"nombre": "ATAQUE CRITICO", "nomenclatura": "AC", "nivel": 3},
    {"nombre": "SANGRADO CERTERO", "nomenclatura": "SC", "nivel": 3},
    {"nombre": "BUFFO DEFENSA FUERTE", "nomenclatura": "BDF", "nivel": 3},
    {"nombre": "BUFFO SUERTE", "nomenclatura": "BS", "nivel": 3},
    {"nombre": "BUFFO LIMPIEZA AZAR", "nomenclatura": "BLA", "nivel": 3},
    {"nombre": "BUFFO VIDA PEQUEÑO", "nomenclatura": "BVP", "nivel": 3},
    {"nombre": "ATAQUE NORMAL + FUEGO AZAR", "nomenclatura": "AN+FA", "nivel": 3},
    {"nombre": "ATAQUE NORMAL + BUFFO DEFENSA", "nomenclatura": "AN+BD", "nivel": 3},
    {"nombre": "Ataque normal + robo carta", "nomenclatura": "AN+RC", "nivel": 3},
    {"nombre": "Ataque ligero + sangrado azar", "nomenclatura": "AL+SA", "nivel": 3},
    {"nombre": "Ataque ligero + congelar azar", "nomenclatura": "AL+CA", "nivel": 3},
    {"nombre": "Ataque ligero + fuego certero", "nomenclatura": "AL+FC", "nivel": 3},
    {
        "nombre": "Ataque ligero + paralizar certero",
        "nomenclatura": "AL+PC",
        "nivel": 3,
    },
    {
        "nombre": "Ataque ligero + buffo defensa normal",
        "nomenclatura": "AL+BDN",
        "nivel": 3,
    },
    {"nombre": "Sangrado azar + fuego azar", "nomenclatura": "SA+FA", "nivel": 3},
    {"nombre": "Sangrado azar + paralizar azar", "nomenclatura": "SA+PA", "nivel": 3},
    {"nombre": "Sangrado azar + buffo defensa ", "nomenclatura": "SA+BD", "nivel": 3},
    {"nombre": "Sangrado azar + robo carta", "nomenclatura": "SA+RC", "nivel": 3},
    {"nombre": "Congelar azar + buffo defensa", "nomenclatura": "CA+BD", "nivel": 3},
    {"nombre": "Congelar azar + robo carta", "nomenclatura": "CA+RC", "nivel": 3},
    {"nombre": "Fuego certero + buffo defensa", "nomenclatura": "FC+BD", "nivel": 3},
    {"nombre": "Fuego certero + robo carta", "nomenclatura": "FC+RC", "nivel": 3},
    {
        "nombre": "Fuego azar + buffo defensa normal",
        "nomenclatura": "FA+BDN",
        "nivel": 3,
    },
    {
        "nombre": "Paralizar certero + buffo defensa",
        "nomenclatura": "PC+BD",
        "nivel": 3,
    },
    {"nombre": "Paralizar certero + robo carta", "nomenclatura": "PC+RC", "nivel": 3},
    {
        "nombre": "Paralizar azar + buffo defensa normal",
        "nomenclatura": "PA+BDN",
        "nivel": 3,
    },
    {
        "nombre": "Buffo defensa normal + robo carta",
        "nomenclatura": "BDN+RC",
        "nivel": 3,
    },
    {"nombre": "ESQUIVAR CERTERO", "nomenclatura": "EC", "nivel": 3},
    {"nombre": "ESQUIVAR AZAR + ATAQUE LIGERO", "nomenclatura": "EA +AL", "nivel": 2},
    {"nombre": "ATAQUE NORMAL", "nomenclatura": "AN", "nivel": 2},
    {"nombre": "SANGRADO AZAR", "nomenclatura": "SA", "nivel": 2},
    {"nombre": "CONGELAR AZAR", "nomenclatura": "CA", "nivel": 2},
    {"nombre": "FUEGO CERTERO", "nomenclatura": "FC", "nivel": 2},
    {"nombre": "PARALIZAR CERTERO", "nomenclatura": "PC", "nivel": 2},
    {"nombre": "BUFFO DEFENSA NORMAL", "nomenclatura": "BDN", "nivel": 2},
    {"nombre": "Ataque ligero + fuego azar", "nomenclatura": "AL+FA", "nivel": 2},
    {"nombre": "Ataque ligero + paralizar azar", "nomenclatura": "AL+PA", "nivel": 2},
    {"nombre": "Ataque ligero + buffo defensa ", "nomenclatura": "AL+BD", "nivel": 2},
    {"nombre": "Ataque ligero + robo de carta", "nomenclatura": "AL+RC", "nivel": 2},
    {"nombre": "Fuego azar + paralizar azar ", "nomenclatura": "FA+PA", "nivel": 2},
    {"nombre": "Fuego azar +buffo defensa", "nomenclatura": "FA+BD", "nivel": 2},
    {"nombre": "Fuego azar + robo carta", "nomenclatura": "FA+RC", "nivel": 2},
    {"nombre": "Paralizar azar + buffo defensa", "nomenclatura": "PA+BD", "nivel": 2},
    {"nombre": "Paralizar azar + robo carta", "nomenclatura": "PA+RC", "nivel": 2},
    {"nombre": "Buffo defensa + robo carta ", "nomenclatura": "BD+RC", "nivel": 2},
    {"nombre": "ATAQUE LIGERO", "nomenclatura": "AL", "nivel": 1},
    {"nombre": "FUEGO AZAR", "nomenclatura": "FA", "nivel": 1},
    {"nombre": "PARALIZAR AZAR", "nomenclatura": "PA", "nivel": 1},
    {"nombre": "BUFFO DEFENSA", "nomenclatura": "BD", "nivel": 1},
    {"nombre": "ESQUIVAR AZAR", "nomenclatura": "EA", "nivel": 1},
    {"nombre": "ROBO CARTA", "nomenclatura": "RC", "nivel": 1},
]

nomenclaturas = [
    {
        "codigo": "AL",
        "categoria": "ataque",
        "nivel": 1,
        "nombre": "Ataque ligero",
        "funcion": "Tu ataque Inflige +1 de daño al oponente.",
    },
    {
        "codigo": "AN",
        "categoria": "ataque",
        "nivel": 2,
        "nombre": "Ataque normal",
        "funcion": "Tu ataque Inflige +2 de daño al oponente.",
    },
    {
        "codigo": "AC",
        "categoria": "ataque",
        "nivel": 3,
        "nombre": "Ataque crítico",
        "funcion": "Tu ataque Inflige +3 de daño al oponente.",
    },
    {
        "codigo": "SA",
        "categoria": "sangrado",
        "nivel": 3,
        "nombre": "Sangrado azar",
        "funcion": "Lanzar dado para aplicar. \nSangrado: 1 de daño a la vida del oponente por 3 turnos seguidos.",
    },
    {
        "codigo": "SC",
        "categoria": "sangrado",
        "nivel": 3,
        "nombre": "Sangrado certero",
        "funcion": "Sangrado: 1 de daño a la vida del oponente por 3 turnos seguidos.",
    },
    {
        "codigo": "FA",
        "categoria": "fuego",
        "nivel": 3,
        "nombre": "Fuego azar",
        "funcion": "Lanzar dado para aplicar. \nFuego: 1 de daño general a tu oponente por 3 turnos seguidos.",
    },
    {
        "codigo": "FC",
        "categoria": "fuego",
        "nivel": 3,
        "nombre": "Fuego certero",
        "funcion": "Fuego: 1 de daño general a tu oponente por 3 turnos seguidos.",
    },
    {
        "codigo": "BD",
        "categoria": "defensa",
        "nivel": 1,
        "nombre": "Bufo defensa",
        "funcion": "Fortalece la Defensa en +1.",
    },
    {
        "codigo": "BDN",
        "categoria": "defensa",
        "nivel": 2,
        "nombre": "Bufo defensa normal",
        "funcion": "Fortalece la Defensa en +2.",
    },
    {
        "codigo": "BDF",
        "categoria": "defensa",
        "nivel": 3,
        "nombre": "Bufo defensa fuerte",
        "funcion": "Fortalece la Defensa en +3.",
    },
    {
        "codigo": "BVP",
        "categoria": "vida",
        "nivel": 1,
        "nombre": "Bufo vida pequeño",
        "funcion": "Aumenta la Vida en +1.",
    },
    {
        "codigo": "BVM",
        "categoria": "vida",
        "nivel": 2,
        "nombre": "Bufo vida mediano",
        "funcion": "Aumenta la Vida en +2.",
    },
    {
        "codigo": "BVG",
        "categoria": "vida",
        "nivel": 3,
        "nombre": "Bufo vida grande",
        "funcion": "Aumenta la Vida en +3.",
    },
    {
        "codigo": "PA",
        "categoria": "paralizar",
        "nivel": 0,
        "nombre": "Paralizar azar",
        "funcion": "Lanzar dado para aplicar.\nParalizar: Tu oponente debe lanzar dado al inicio de su turno para poder jugar. Duración: 2 turnos.",
    },
    {
        "codigo": "PC",
        "categoria": "paralizar",
        "nivel": 0,
        "nombre": "Paralizar certero",
        "funcion": "Paralizar: Tu oponente debe lanzar dado al inicio de su turno para poder jugar. Duración: 2 turnos.",
    },
    {
        "codigo": "CA",
        "categoria": "congelar",
        "nivel": 0,
        "nombre": "Congelar azar",
        "funcion": "Lanzar dado para aplicar.\nCongelar: El oponente no puede jugar su próximo turno.",
    },
    {
        "codigo": "CC",
        "categoria": "congelar",
        "nivel": 0,
        "nombre": "Congelar certero",
        "funcion": "Congelar: El oponente no puede jugar su próximo turno.",
    },
    {
        "codigo": "BLA",
        "categoria": "limpieza",
        "nivel": 0,
        "nombre": "Bufo limpieza azar",
        "funcion": "Lanzar dado para aplicar. \nLimpieza: Elimina todos los estados alterados aplicados.",
    },
    {
        "codigo": "BS",
        "categoria": "suerte",
        "nivel": 0,
        "nombre": "Bufo suerte",
        "funcion": "Al lanzar dados necesitas desde 4 para aplicar acciones. Duración: 4 turnos seguidos.",
    },
    {
        "codigo": "EA",
        "categoria": "esquivar",
        "nivel": 0,
        "nombre": "Esquivar azar",
        "funcion": "Lanzar dado para aplicar. \nEsquivas el ataque de tu oponente.",
    },
    {
        "codigo": "EC",
        "categoria": "estquivar",
        "nivel": 0,
        "nombre": "Esquivar certero",
        "funcion": "Esquivas el ataque de tu oponente.",
    },
    {
        "codigo": "RC",
        "categoria": "robar",
        "nivel": 0,
        "nombre": "Robo carta",
        "funcion": "Cada jugador roba una carta.",
    },
]

distribucion_equipamiento = {
    "Armas": {5: 1, 4: 2, 3: 3, 2: 4, 1: 5},
    "Pechera": {5: 1, 4: 1, 3: 1, 2: 1, 1: 2},
    "Casco": {3: 1, 2: 1, 1: 1},
    "Botas": {3: 1, 2: 1, 1: 1},
    "Guantes": {3: 1, 2: 1, 1: 1},
}

equipamiento_sets = {
    "ARMA": [
        ["ARMA"],
        ["AC+PC"],
        ["SC+BD", "AN+SA"],
        ["AN+FA", "AC", "AC"],
        ["EA +AL", "AN", "BDN", "FC"],
        ["AL", "PA", "BD", "AL", "AL"],
    ],
    "BOTAS": [["BOTAS"], [], [], ["BDF"], ["BDN"], ["EA"]],
    "CASCO": [["CASCO"], [], [], ["BS"], ["SA"], ["AL"]],
    "PECHERA": [["PECHERA"], ["AC+FC"], ["AC+PA"], ["BLA"], ["AN"], ["AL", "BD"]],
    "GUANTES": [["GUANTES"], [], [], ["BVP"], ["AN"], ["AL"]],
}

equipamiento_sets_nominales = {
    "Karsuk Jairuk": {
        "ARMA": [
            "AC+PC",
            "SC+BD",
            "AN+SA",
            "AN+FA",
            "AC",
            "AC",
            "EA+AL",
            "AN",
            "BDN",
            "FC",
            "AL",
            "PA",
            "BD",
            "AL",
            "AL",
        ],
        "BOTAS": ["BDF", "BDN", "EA"],
        "CASCO": ["BS", "SA", "AL"],
        "PECHERA": ["AC+FC", "AC+PA", "BLA", "AN", "AL", "BD"],
        "GUANTES": ["BVP", "AN", "AL"],
    },
    "Exilte Naor": {
        "ARMA": [
            "AC+FC",
            "AC+RC",
            "CC",
            "SC",
            "AL+SA",
            "BLA",
            "AN",
            "AN",
            "AL+PA",
            "SA",
            "BD",
            "BD",
            "AL",
            "AL",
            "AL",
        ],
        "BOTAS": ["AL+CA", "FA+PA", "PA"],
        "CASCO": ["BS", "EA+AL", "AL"],
        "PECHERA": ["AN+SC", "AL+BLA", "BLA", "AN", "EA", "BD"],
        "GUANTES": ["AC", "BDN", "BD"],
    },
    "Nishuk Ashai": {
        "ARMA": [
            "SC+FC",
            "AN+SA",
            "AC+PA",
            "AL+CA",
            "AC",
            "PC+BD",
            "FA+PA",
            "AN",
            "AN",
            "PC",
            "AL",
            "BD",
            "FA",
            "AL",
            "PA",
        ],
        "BOTAS": ["BDF", "FA+BD", "EA"],
        "CASCO": ["BS", "AL+RC", "AL"],
        "PECHERA": ["AC+FC", "BVM", "BLA", "CA", "AL", "PA"],
        "GUANTES": ["BDF", "BDN", "BD"],
    },
    'Uke Gajur': {
        'ARMA':    [
            'AN+BDF', 
            'AN+BDN', 
            'AC+PA', 
            'AC', 
            'SC', 
            'BDF', 
            'SA', 
            'BDN', 
            'EA+AL', 
            'EA+PC', 
            'AL', 
            'BD', 
            'EA', 
            'AL', 
            'PA'
        ],
        'BOTAS':   ['AC', 'EA'],
        'CASCO':   ['AL+SA', 'AL+BD', 'AL'],
        'PECHERA': ['BVG', 'AN+SA', 'BDF', 'AN', 'PA', 'AL'],
        'GUANTES': ['BLA', 'SA', 'AL']
        },
    'Rougur Ivaiesk': {
        'ARMA':    [
            'AC+FC', 
            'FC+PC', 
            'AN+CA', 
            'BLA', 
            'BS', 
            'AC', 
            'AL+FA', 
            'BDN', 
            'AL+PA', 
            'AN', 
            'BD', 
            'AL', 
            'FA', 
            'PA', 
            'EA'
        ],
        'BOTAS':   ['SC', 'AN', 'FA'],
        'CASCO':   ['BS', 'AL+RC', 'AL'],
        'PECHERA': ['SC+FC', 'PC+BDN', 'AC', 'PC', 'EA', 'AL'],
        'GUANTES': ['BLA', 'FC', 'BD']
        }
    }
